// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using examen.ContextModels;

#nullable disable

namespace examen.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20240125122648_migration2")]
    partial class migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("examen.Entities.Autor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Edituraid")
                        .HasColumnType("int");

                    b.Property<int>("editura_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Edituraid");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("examen.Entities.Carte", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Edituraid")
                        .HasColumnType("int");

                    b.Property<int>("editura_id")
                        .HasColumnType("int");

                    b.Property<string>("titlu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Edituraid");

                    b.ToTable("Carte");
                });

            modelBuilder.Entity("examen.Entities.Editura", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Editura");
                });

            modelBuilder.Entity("examen.Entities.Autor", b =>
                {
                    b.HasOne("examen.Entities.Editura", null)
                        .WithMany("Autori")
                        .HasForeignKey("Edituraid");
                });

            modelBuilder.Entity("examen.Entities.Carte", b =>
                {
                    b.HasOne("examen.Entities.Editura", null)
                        .WithMany("Carti")
                        .HasForeignKey("Edituraid");
                });

            modelBuilder.Entity("examen.Entities.Editura", b =>
                {
                    b.Navigation("Autori");

                    b.Navigation("Carti");
                });
#pragma warning restore 612, 618
        }
    }
}
